[2021-05-27 14:49:03,287] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: dag_transfers_scraping.send_transfers_file_to_S3 2021-05-27T14:48:57.647953+00:00 [queued]>
[2021-05-27 14:49:03,303] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: dag_transfers_scraping.send_transfers_file_to_S3 2021-05-27T14:48:57.647953+00:00 [queued]>
[2021-05-27 14:49:03,303] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-05-27 14:49:03,303] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-05-27 14:49:03,303] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-05-27 14:49:03,312] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): send_transfers_file_to_S3> on 2021-05-27T14:48:57.647953+00:00
[2021-05-27 14:49:03,319] {standard_task_runner.py:52} INFO - Started process 79342 to run task
[2021-05-27 14:49:03,323] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag_transfers_scraping', 'send_transfers_file_to_S3', '2021-05-27T14:48:57.647953+00:00', '--job-id', '69', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_transfers_scraping.py', '--cfg-path', '/tmp/tmp8xsycadh', '--error-file', '/tmp/tmp84fi9eud']
[2021-05-27 14:49:03,323] {standard_task_runner.py:77} INFO - Job 69: Subtask send_transfers_file_to_S3
[2021-05-27 14:49:03,362] {logging_mixin.py:104} INFO - Running <TaskInstance: dag_transfers_scraping.send_transfers_file_to_S3 2021-05-27T14:48:57.647953+00:00 [running]> on host f7393dd572fa
[2021-05-27 14:49:03,404] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_transfers_scraping
AIRFLOW_CTX_TASK_ID=send_transfers_file_to_S3
AIRFLOW_CTX_EXECUTION_DATE=2021-05-27T14:48:57.647953+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-27T14:48:57.647953+00:00
[2021-05-27 14:49:03,405] {base_aws.py:368} INFO - Airflow Connection: aws_conn_id=aws_s3_***_user
[2021-05-27 14:49:03,412] {base_aws.py:170} INFO - Credentials retrieved from extra_config
[2021-05-27 14:49:03,412] {base_aws.py:87} INFO - Creating session with aws_access_key_id=AKIAZP4IG4HNCZJ3LJDL region_name=None
[2021-05-27 14:49:03,425] {base_aws.py:157} INFO - role_arn is None
[2021-05-27 14:49:04,082] {python.py:151} INFO - Done. Returned value was: None
[2021-05-27 14:49:04,119] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=dag_transfers_scraping, task_id=send_transfers_file_to_S3, execution_date=20210527T144857, start_date=20210527T144903, end_date=20210527T144904
[2021-05-27 14:49:04,149] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-05-27 14:49:04,176] {local_task_job.py:151} INFO - Task exited with return code 0
