[2021-05-27 14:15:16,841] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: dag_transfers_scraping.send_transfers_file_to_S3 2021-05-27T14:15:11.940175+00:00 [queued]>
[2021-05-27 14:15:16,853] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: dag_transfers_scraping.send_transfers_file_to_S3 2021-05-27T14:15:11.940175+00:00 [queued]>
[2021-05-27 14:15:16,854] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-05-27 14:15:16,854] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-05-27 14:15:16,854] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-05-27 14:15:16,860] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): send_transfers_file_to_S3> on 2021-05-27T14:15:11.940175+00:00
[2021-05-27 14:15:16,866] {standard_task_runner.py:52} INFO - Started process 76397 to run task
[2021-05-27 14:15:16,868] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'dag_transfers_scraping', 'send_transfers_file_to_S3', '2021-05-27T14:15:11.940175+00:00', '--job-id', '66', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_transfers_scraping.py', '--cfg-path', '/tmp/tmptz_eg1a_', '--error-file', '/tmp/tmp89n0k3po']
[2021-05-27 14:15:16,869] {standard_task_runner.py:77} INFO - Job 66: Subtask send_transfers_file_to_S3
[2021-05-27 14:15:16,898] {logging_mixin.py:104} INFO - Running <TaskInstance: dag_transfers_scraping.send_transfers_file_to_S3 2021-05-27T14:15:11.940175+00:00 [running]> on host f7393dd572fa
[2021-05-27 14:15:16,933] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_transfers_scraping
AIRFLOW_CTX_TASK_ID=send_transfers_file_to_S3
AIRFLOW_CTX_EXECUTION_DATE=2021-05-27T14:15:11.940175+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-27T14:15:11.940175+00:00
[2021-05-27 14:15:16,935] {base_aws.py:368} INFO - Airflow Connection: aws_conn_id=aws_s3_***_user
[2021-05-27 14:15:16,941] {base_aws.py:170} INFO - Credentials retrieved from extra_config
[2021-05-27 14:15:16,941] {base_aws.py:87} INFO - Creating session with aws_access_key_id=AKIAZP4IG4HNCZJ3LJDL region_name=None
[2021-05-27 14:15:16,953] {base_aws.py:157} INFO - role_arn is None
[2021-05-27 14:15:17,533] {python.py:151} INFO - Done. Returned value was: None
[2021-05-27 14:15:17,540] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=dag_transfers_scraping, task_id=send_transfers_file_to_S3, execution_date=20210527T141511, start_date=20210527T141516, end_date=20210527T141517
[2021-05-27 14:15:17,561] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-05-27 14:15:17,600] {local_task_job.py:151} INFO - Task exited with return code 0
